### ISSUE TITLE
Error with primenet.py

### ISSUE THREAD

**Issue by mocallins** [tdulcet/Distributed-Computing-Scripts#22]
Output from  wget https://raw.github.com/tdulcet/Linux-System-Information/master/info.sh -qO - | bash -s

```Linux Distribution:             Raspbian GNU/Linux 11 (bullseye)
Linux Kernel:                   6.1.21+
Computer Model:                 Raspberry Pi Zero Rev 1.3
Processor (CPU):                ARMv6-compatible processor rev 7 (v6l)
CPU Sockets/Cores/Threads:      1/1/1
Architecture:                   armv6l-linux (32-bit)
Total memory (RAM):             477 MiB (500 MB)
Total swap space:               0 MiB (0 MB)
Disk space:                     mmcblk0: 15,238 MiB (15GiB) (15,978 MB (16GB))
Computer name:                  compute1
Network name (SSID):            collins2.4
Hostname:                       compute1
IPv4 address:                   wlan0: 192.168.0.45
MAC address:                    wlan0: 20:e5:2a:76:a4:96
Computer ID:                    e827c50d08394350878e5cdb82a1db73
Time zone:                      America/Chicago (CST, -0600)
Language:                       en_US.UTF-8
Bash Version:                   5.1.4(1)-release
Terminal:                       xterm (Bitvise SSH Client)
```

Error from: nohup ~/prime95/primenet.py -w ~/prime95 --num-workers 1 >> primenet.out &
```
connectionpool.py: [MainThread 2024-03-08 11:46:37,341]  DEBUG: Starting new HTTPS connection (1): www.mersenne.org:443
connectionpool.py: [MainThread 2024-03-08 11:46:38,232]  DEBUG: https://www.mersenne.org:443 "POST /default.php HTTP/1.1" 200 8195
primenet.py: [MainThread 2024-03-08 11:46:38,285]  DEBUG: No new results in './results.txt'.
primenet.py: [MainThread 2024-03-08 11:46:38,295]  DEBUG: Found 0 < 2 assignments in './worktodo.txt', getting 2 new assignments
Traceback (most recent call last):
  File "/home/pi/prime95/wrk0/../primenet.py", line 3320, in <module>
    got = get_assignments(adir, cpu_num, progress, tasks)
  File "/home/pi/prime95/wrk0/../primenet.py", line 2324, in get_assignments
    assignments = primenet_fetch(cpu_num, num_to_get)
  File "/home/pi/prime95/wrk0/../primenet.py", line 2238, in primenet_fetch
    ("cores", options.num_workers),
AttributeError: 'Values' object has no attribute 'num_workers'
```

Anything else you might need, just let me know

**Comment by tdulcet** [comment]
Thanks for the detailed bug report! I am sorry that our PrimeNet script did not work for you. I have been simultaneously working on multiple versions of the script and it looks like I accidentally include a change in the 1.2.3 update yesterday that was actually meant for version 2.0. I will fix this later today...

Note that this code path in the script is for the deprecated and not recommended manual testing feature. Since you are running it on a Raspberry Pi, presumably you are using it with Mlucas and thus you should not need to do manual testing. Just remove the `password` line from your `local.ini` file and the script will use the PrimeNet API, which should work as expected.

**Comment by tdulcet** [comment]
I fixed the manual testing feature of the script in https://github.com/tdulcet/Distributed-Computing-Scripts/commit/f88322628103c8d1b73768578caee3c612959fd1.
